### ISSUE TITLE
Missing GitHub Provider

### ISSUE THREAD

**Issue by felipebonezi** [play-rconf/play-rconf-sdk#1]
@thibaultmeyer I have some config files over GitHub repository and Spring Boot has this capability to read the config file from the GitHub repository.

I'm thinking to implement a `GitHubProvider` to the Play-RConf project.
How do you feel about it? Is it a good idea? Which project do I need a fork to create this provider?

**Comment by thibaultmeyer** [comment]
Hello,

It's a good idea and I think it's possible to make the plugin more generic to work with git regardless of the provider.

You just need. Create a Maven project that uses the play-rconf-sdk dependency. You can look at the code of other plug-ins to help you.

I will create a new repository for this new plugin. In the meantime, you can rely on the structure of one of the other plugins

**Comment by felipebonezi** [comment]
@thibaultmeyer can you put a README so that a can fork the git plugin repo?

**Comment by thibaultmeyer** [comment]
The created repository : https://github.com/play-rconf/play-rconf-git

**Comment by felipebonezi** [comment]
@thibaultmeyer I'd implemented GitProvider and worked nicely with Github over three modes:

1. Public repository
2. Private repository using Login/Pass
3. Private repository using SSH-RSA

But I got a problem to implement the second and third Test implementation.

How can we wrote a valid test to those cases without exposes an User or a RSA Private Key? 👀🤔

**Comment by thibaultmeyer** [comment]
@felipebonezi

For your unit tests, you can mimic existing (like DynamoDB or etcd). By example, on DynamoDB, we are using ENV variables (https://github.com/play-rconf/play-rconf-dynamodb/blob/master/src/test/java/io/playrconf/provider/DynamoDbProviderTest.java). These environment variables are defined in TravisCI (secret key).

You can use your own value on your computer (local) and I will configure TravisCI once the first commit has been made. For the public repository test, you can store "test" configuration file on ".github" directory in "play-rconf-git" repository. I will create a private repository and a "dummy" github user on my side to use with TravisCI.

Dont worry if your merge request unit tests fail, I will force merge and do TravisCI configuration later.

**Comment by felipebonezi** [comment]
@thibaultmeyer ok, good idea, but I implemented the SSH-RSA reading a file path not the file content.

I think that I need to refactor this logic, right?

**Comment by thibaultmeyer** [comment]
If you can refacto to handle the two ways: from file and from content. It could be nice.

**Comment by thibaultmeyer** [comment]
PR : https://github.com/play-rconf/play-rconf-git/pull/1
